kind: PersistentVolume
apiVersion: v1
metadata:
  name: memcached-cluster-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/mnt/data"
    server: mcrouter-nfs-server
