---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: memcached
  labels:
    name: memcached-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.4-alpine
        ports:
        - containerPort: 11211
---
# This creates a headless service that allows us to look up all memcached instances via k8s DNS
#
# i.e.
# `nslookup memcached-service`
kind: Service
apiVersion: v1
metadata:
  name: memcached-service
  labels:
    name: memcached-deployment-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  selector:
    app: memcached
