kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mcrouter-provisioner
  labels:
    name: mcrouter-provisioner-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mcrouter-provisioner
    spec:
      volumes:
        - name: mcrouter-provisioner-storage
          emptyDir: {}
      containers:
      - name: mcrouter-provisioner
        image: mlaccetti/mcrouter-kubernetes-provisioner:master
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/mcrouter"
          name: mcrouter-provisioner-storage
          readOnly: false
