---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mcrouter
  labels:
    name: mcrouter-deployment
    project: mcrouter-memcached
    role: mcrouter
spec:
  replicas: 3
  selector:
    matchLabels:
      project: mcrouter-memcached
      role: mcrouter
  template:
    metadata:
      labels:
        project: mcrouter-memcached
        role: mcrouter
    spec:
      volumes:
      - name: mcrouter-provisioner-storage
        emptyDir: {}
      containers:
      - name: mcrouter
        image: jamescarr/mcrouter:1.0.1
        command: ["tail","-f", "/dev/null"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/mcrouter"
          name: mcrouter-provisioner-storage
          readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  name: mcrouter-service
  labels:
    project: mcrouter-memcached
    role: mcrouter
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    project: mcrouter-memcached
    role: mcrouter
