kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mcrouter-provisioner
  labels:
    name: mcrouter-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mcrouter
    spec:
      volumes:
        - name: mcrouter-provisioner-pv-storage
          persistentVolumeClaim:
            claimName: memcached-cluster-pvc
      containers:
      - name: mcrouter-provisioner
        image: mlaccetti/mcrouter-kubernetes-provisioner:master
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/srv/nfs"
          name: mcrouter-provisioner-pv-storage
