kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mcrouter-iscsi-server
  labels:
    name: iscsi-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iscsi-server
    spec:
      containers:
        - name: iscsi-server
          image: fabiand/iscsi-demo-target-tgtd:latest
